// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GlobalTransactionStatusType int32

const (
	GlobalTransactionStatusType_INIT                          GlobalTransactionStatusType = 0
	GlobalTransactionStatusType_PRIMARY_TRANSACTION_PREPARED  GlobalTransactionStatusType = 1
	GlobalTransactionStatusType_PRIMARY_TRANSACTION_COMMITTED GlobalTransactionStatusType = 2
	GlobalTransactionStatusType_PRIMARY_TRANSACTION_CANCELED  GlobalTransactionStatusType = 3
)

var GlobalTransactionStatusType_name = map[int32]string{
	0: "INIT",
	1: "PRIMARY_TRANSACTION_PREPARED",
	2: "PRIMARY_TRANSACTION_COMMITTED",
	3: "PRIMARY_TRANSACTION_CANCELED",
}

var GlobalTransactionStatusType_value = map[string]int32{
	"INIT":                          0,
	"PRIMARY_TRANSACTION_PREPARED":  1,
	"PRIMARY_TRANSACTION_COMMITTED": 2,
	"PRIMARY_TRANSACTION_CANCELED":  3,
}

func (x GlobalTransactionStatusType) String() string {
	return proto.EnumName(GlobalTransactionStatusType_name, int32(x))
}

func (GlobalTransactionStatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type BranchTransactionResponse_Status int32

const (
	BranchTransactionResponse_SUCCESS BranchTransactionResponse_Status = 0
	BranchTransactionResponse_FAILED  BranchTransactionResponse_Status = 1
)

var BranchTransactionResponse_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
}

var BranchTransactionResponse_Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAILED":  1,
}

func (x BranchTransactionResponse_Status) String() string {
	return proto.EnumName(BranchTransactionResponse_Status_name, int32(x))
}

func (BranchTransactionResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4, 0}
}

type Lock struct {
	PrimaryPrepareTxId   *TransactionID `protobuf:"bytes,1,opt,name=primary_prepare_tx_id,json=primaryPrepareTxId,proto3" json:"primary_prepare_tx_id,omitempty"`
	PrevState            []byte         `protobuf:"bytes,2,opt,name=prev_state,json=prevState,proto3" json:"prev_state,omitempty"`
	UpdatingState        []byte         `protobuf:"bytes,3,opt,name=updating_state,json=updatingState,proto3" json:"updating_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Lock) Reset()         { *m = Lock{} }
func (m *Lock) String() string { return proto.CompactTextString(m) }
func (*Lock) ProtoMessage()    {}
func (*Lock) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Lock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lock.Unmarshal(m, b)
}
func (m *Lock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lock.Marshal(b, m, deterministic)
}
func (m *Lock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lock.Merge(m, src)
}
func (m *Lock) XXX_Size() int {
	return xxx_messageInfo_Lock.Size(m)
}
func (m *Lock) XXX_DiscardUnknown() {
	xxx_messageInfo_Lock.DiscardUnknown(m)
}

var xxx_messageInfo_Lock proto.InternalMessageInfo

func (m *Lock) GetPrimaryPrepareTxId() *TransactionID {
	if m != nil {
		return m.PrimaryPrepareTxId
	}
	return nil
}

func (m *Lock) GetPrevState() []byte {
	if m != nil {
		return m.PrevState
	}
	return nil
}

func (m *Lock) GetUpdatingState() []byte {
	if m != nil {
		return m.UpdatingState
	}
	return nil
}

type GlobalTransaction struct {
	PrimaryPrepareTxId   *TransactionID       `protobuf:"bytes,1,opt,name=primary_prepare_tx_id,json=primaryPrepareTxId,proto3" json:"primary_prepare_tx_id,omitempty"`
	PrimaryCommitTx      *BranchTransaction   `protobuf:"bytes,2,opt,name=primary_commit_tx,json=primaryCommitTx,proto3" json:"primary_commit_tx,omitempty"`
	PrimaryRollbackTx    *BranchTransaction   `protobuf:"bytes,3,opt,name=primary_rollback_tx,json=primaryRollbackTx,proto3" json:"primary_rollback_tx,omitempty"`
	BranchPrepareTxs     []*BranchTransaction `protobuf:"bytes,4,rep,name=branch_prepare_txs,json=branchPrepareTxs,proto3" json:"branch_prepare_txs,omitempty"`
	BranchCommitTxs      []*BranchTransaction `protobuf:"bytes,5,rep,name=branch_commit_txs,json=branchCommitTxs,proto3" json:"branch_commit_txs,omitempty"`
	BranchRollbackTxs    []*BranchTransaction `protobuf:"bytes,6,rep,name=branch_rollback_txs,json=branchRollbackTxs,proto3" json:"branch_rollback_txs,omitempty"`
	TtlHeight            uint64               `protobuf:"varint,7,opt,name=ttl_height,json=ttlHeight,proto3" json:"ttl_height,omitempty"`
	TtlTime              *timestamp.Timestamp `protobuf:"bytes,8,opt,name=ttl_time,json=ttlTime,proto3" json:"ttl_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GlobalTransaction) Reset()         { *m = GlobalTransaction{} }
func (m *GlobalTransaction) String() string { return proto.CompactTextString(m) }
func (*GlobalTransaction) ProtoMessage()    {}
func (*GlobalTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *GlobalTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalTransaction.Unmarshal(m, b)
}
func (m *GlobalTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalTransaction.Marshal(b, m, deterministic)
}
func (m *GlobalTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalTransaction.Merge(m, src)
}
func (m *GlobalTransaction) XXX_Size() int {
	return xxx_messageInfo_GlobalTransaction.Size(m)
}
func (m *GlobalTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalTransaction proto.InternalMessageInfo

func (m *GlobalTransaction) GetPrimaryPrepareTxId() *TransactionID {
	if m != nil {
		return m.PrimaryPrepareTxId
	}
	return nil
}

func (m *GlobalTransaction) GetPrimaryCommitTx() *BranchTransaction {
	if m != nil {
		return m.PrimaryCommitTx
	}
	return nil
}

func (m *GlobalTransaction) GetPrimaryRollbackTx() *BranchTransaction {
	if m != nil {
		return m.PrimaryRollbackTx
	}
	return nil
}

func (m *GlobalTransaction) GetBranchPrepareTxs() []*BranchTransaction {
	if m != nil {
		return m.BranchPrepareTxs
	}
	return nil
}

func (m *GlobalTransaction) GetBranchCommitTxs() []*BranchTransaction {
	if m != nil {
		return m.BranchCommitTxs
	}
	return nil
}

func (m *GlobalTransaction) GetBranchRollbackTxs() []*BranchTransaction {
	if m != nil {
		return m.BranchRollbackTxs
	}
	return nil
}

func (m *GlobalTransaction) GetTtlHeight() uint64 {
	if m != nil {
		return m.TtlHeight
	}
	return 0
}

func (m *GlobalTransaction) GetTtlTime() *timestamp.Timestamp {
	if m != nil {
		return m.TtlTime
	}
	return nil
}

type Invocation struct {
	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Func                 string   `protobuf:"bytes,2,opt,name=func,proto3" json:"func,omitempty"`
	Args                 [][]byte `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Invocation) Reset()         { *m = Invocation{} }
func (m *Invocation) String() string { return proto.CompactTextString(m) }
func (*Invocation) ProtoMessage()    {}
func (*Invocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *Invocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invocation.Unmarshal(m, b)
}
func (m *Invocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invocation.Marshal(b, m, deterministic)
}
func (m *Invocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invocation.Merge(m, src)
}
func (m *Invocation) XXX_Size() int {
	return xxx_messageInfo_Invocation.Size(m)
}
func (m *Invocation) XXX_DiscardUnknown() {
	xxx_messageInfo_Invocation.DiscardUnknown(m)
}

var xxx_messageInfo_Invocation proto.InternalMessageInfo

func (m *Invocation) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Invocation) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *Invocation) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

type BranchTransaction struct {
	TxId                 *TransactionID `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Invocation           *Invocation    `protobuf:"bytes,2,opt,name=invocation,proto3" json:"invocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BranchTransaction) Reset()         { *m = BranchTransaction{} }
func (m *BranchTransaction) String() string { return proto.CompactTextString(m) }
func (*BranchTransaction) ProtoMessage()    {}
func (*BranchTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *BranchTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchTransaction.Unmarshal(m, b)
}
func (m *BranchTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchTransaction.Marshal(b, m, deterministic)
}
func (m *BranchTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchTransaction.Merge(m, src)
}
func (m *BranchTransaction) XXX_Size() int {
	return xxx_messageInfo_BranchTransaction.Size(m)
}
func (m *BranchTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_BranchTransaction proto.InternalMessageInfo

func (m *BranchTransaction) GetTxId() *TransactionID {
	if m != nil {
		return m.TxId
	}
	return nil
}

func (m *BranchTransaction) GetInvocation() *Invocation {
	if m != nil {
		return m.Invocation
	}
	return nil
}

type BranchTransactionResponse struct {
	Id                   string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               BranchTransactionResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=pb.BranchTransactionResponse_Status" json:"status,omitempty"`
	Proof                []byte                           `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *BranchTransactionResponse) Reset()         { *m = BranchTransactionResponse{} }
func (m *BranchTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*BranchTransactionResponse) ProtoMessage()    {}
func (*BranchTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *BranchTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchTransactionResponse.Unmarshal(m, b)
}
func (m *BranchTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchTransactionResponse.Marshal(b, m, deterministic)
}
func (m *BranchTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchTransactionResponse.Merge(m, src)
}
func (m *BranchTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_BranchTransactionResponse.Size(m)
}
func (m *BranchTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BranchTransactionResponse proto.InternalMessageInfo

func (m *BranchTransactionResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BranchTransactionResponse) GetStatus() BranchTransactionResponse_Status {
	if m != nil {
		return m.Status
	}
	return BranchTransactionResponse_SUCCESS
}

func (m *BranchTransactionResponse) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

type PrimaryLockMeta struct {
	Xid                  string   `protobuf:"bytes,1,opt,name=xid,proto3" json:"xid,omitempty"`
	Chain                string   `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimaryLockMeta) Reset()         { *m = PrimaryLockMeta{} }
func (m *PrimaryLockMeta) String() string { return proto.CompactTextString(m) }
func (*PrimaryLockMeta) ProtoMessage()    {}
func (*PrimaryLockMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *PrimaryLockMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimaryLockMeta.Unmarshal(m, b)
}
func (m *PrimaryLockMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimaryLockMeta.Marshal(b, m, deterministic)
}
func (m *PrimaryLockMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimaryLockMeta.Merge(m, src)
}
func (m *PrimaryLockMeta) XXX_Size() int {
	return xxx_messageInfo_PrimaryLockMeta.Size(m)
}
func (m *PrimaryLockMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimaryLockMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PrimaryLockMeta proto.InternalMessageInfo

func (m *PrimaryLockMeta) GetXid() string {
	if m != nil {
		return m.Xid
	}
	return ""
}

func (m *PrimaryLockMeta) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

type URI struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Chain                string   `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *URI) Reset()         { *m = URI{} }
func (m *URI) String() string { return proto.CompactTextString(m) }
func (*URI) ProtoMessage()    {}
func (*URI) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *URI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_URI.Unmarshal(m, b)
}
func (m *URI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_URI.Marshal(b, m, deterministic)
}
func (m *URI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_URI.Merge(m, src)
}
func (m *URI) XXX_Size() int {
	return xxx_messageInfo_URI.Size(m)
}
func (m *URI) XXX_DiscardUnknown() {
	xxx_messageInfo_URI.DiscardUnknown(m)
}

var xxx_messageInfo_URI proto.InternalMessageInfo

func (m *URI) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *URI) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

type TransactionID struct {
	Uri                  *URI     `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionID) Reset()         { *m = TransactionID{} }
func (m *TransactionID) String() string { return proto.CompactTextString(m) }
func (*TransactionID) ProtoMessage()    {}
func (*TransactionID) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *TransactionID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionID.Unmarshal(m, b)
}
func (m *TransactionID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionID.Marshal(b, m, deterministic)
}
func (m *TransactionID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionID.Merge(m, src)
}
func (m *TransactionID) XXX_Size() int {
	return xxx_messageInfo_TransactionID.Size(m)
}
func (m *TransactionID) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionID.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionID proto.InternalMessageInfo

func (m *TransactionID) GetUri() *URI {
	if m != nil {
		return m.Uri
	}
	return nil
}

func (m *TransactionID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PrimaryTransactionPreparedEvent struct {
	PrimaryPrepareTxId   *TransactionID       `protobuf:"bytes,1,opt,name=primary_prepare_tx_id,json=primaryPrepareTxId,proto3" json:"primary_prepare_tx_id,omitempty"`
	PrimaryCommitTx      *BranchTransaction   `protobuf:"bytes,2,opt,name=primary_commit_tx,json=primaryCommitTx,proto3" json:"primary_commit_tx,omitempty"`
	PrimaryRollbackTx    *BranchTransaction   `protobuf:"bytes,3,opt,name=primary_rollback_tx,json=primaryRollbackTx,proto3" json:"primary_rollback_tx,omitempty"`
	BranchPrepareTxs     []*BranchTransaction `protobuf:"bytes,4,rep,name=branch_prepare_txs,json=branchPrepareTxs,proto3" json:"branch_prepare_txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PrimaryTransactionPreparedEvent) Reset()         { *m = PrimaryTransactionPreparedEvent{} }
func (m *PrimaryTransactionPreparedEvent) String() string { return proto.CompactTextString(m) }
func (*PrimaryTransactionPreparedEvent) ProtoMessage()    {}
func (*PrimaryTransactionPreparedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *PrimaryTransactionPreparedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimaryTransactionPreparedEvent.Unmarshal(m, b)
}
func (m *PrimaryTransactionPreparedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimaryTransactionPreparedEvent.Marshal(b, m, deterministic)
}
func (m *PrimaryTransactionPreparedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimaryTransactionPreparedEvent.Merge(m, src)
}
func (m *PrimaryTransactionPreparedEvent) XXX_Size() int {
	return xxx_messageInfo_PrimaryTransactionPreparedEvent.Size(m)
}
func (m *PrimaryTransactionPreparedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimaryTransactionPreparedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PrimaryTransactionPreparedEvent proto.InternalMessageInfo

func (m *PrimaryTransactionPreparedEvent) GetPrimaryPrepareTxId() *TransactionID {
	if m != nil {
		return m.PrimaryPrepareTxId
	}
	return nil
}

func (m *PrimaryTransactionPreparedEvent) GetPrimaryCommitTx() *BranchTransaction {
	if m != nil {
		return m.PrimaryCommitTx
	}
	return nil
}

func (m *PrimaryTransactionPreparedEvent) GetPrimaryRollbackTx() *BranchTransaction {
	if m != nil {
		return m.PrimaryRollbackTx
	}
	return nil
}

func (m *PrimaryTransactionPreparedEvent) GetBranchPrepareTxs() []*BranchTransaction {
	if m != nil {
		return m.BranchPrepareTxs
	}
	return nil
}

type PrimaryTransactionConfirmedEvent struct {
	PrimaryConfirmTxId        *TransactionID       `protobuf:"bytes,1,opt,name=primary_confirm_tx_id,json=primaryConfirmTxId,proto3" json:"primary_confirm_tx_id,omitempty"`
	BranchCommitOrRollbackTxs []*BranchTransaction `protobuf:"bytes,2,rep,name=branch_commit_or_rollback_txs,json=branchCommitOrRollbackTxs,proto3" json:"branch_commit_or_rollback_txs,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}             `json:"-"`
	XXX_unrecognized          []byte               `json:"-"`
	XXX_sizecache             int32                `json:"-"`
}

func (m *PrimaryTransactionConfirmedEvent) Reset()         { *m = PrimaryTransactionConfirmedEvent{} }
func (m *PrimaryTransactionConfirmedEvent) String() string { return proto.CompactTextString(m) }
func (*PrimaryTransactionConfirmedEvent) ProtoMessage()    {}
func (*PrimaryTransactionConfirmedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *PrimaryTransactionConfirmedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimaryTransactionConfirmedEvent.Unmarshal(m, b)
}
func (m *PrimaryTransactionConfirmedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimaryTransactionConfirmedEvent.Marshal(b, m, deterministic)
}
func (m *PrimaryTransactionConfirmedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimaryTransactionConfirmedEvent.Merge(m, src)
}
func (m *PrimaryTransactionConfirmedEvent) XXX_Size() int {
	return xxx_messageInfo_PrimaryTransactionConfirmedEvent.Size(m)
}
func (m *PrimaryTransactionConfirmedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimaryTransactionConfirmedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PrimaryTransactionConfirmedEvent proto.InternalMessageInfo

func (m *PrimaryTransactionConfirmedEvent) GetPrimaryConfirmTxId() *TransactionID {
	if m != nil {
		return m.PrimaryConfirmTxId
	}
	return nil
}

func (m *PrimaryTransactionConfirmedEvent) GetBranchCommitOrRollbackTxs() []*BranchTransaction {
	if m != nil {
		return m.BranchCommitOrRollbackTxs
	}
	return nil
}

type BranchTransactionPreparedEvent struct {
	PrimaryPrepareTxId   *TransactionID     `protobuf:"bytes,1,opt,name=primary_prepare_tx_id,json=primaryPrepareTxId,proto3" json:"primary_prepare_tx_id,omitempty"`
	CommitTx             *BranchTransaction `protobuf:"bytes,2,opt,name=commit_tx,json=commitTx,proto3" json:"commit_tx,omitempty"`
	RollbackTx           *BranchTransaction `protobuf:"bytes,3,opt,name=rollback_tx,json=rollbackTx,proto3" json:"rollback_tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BranchTransactionPreparedEvent) Reset()         { *m = BranchTransactionPreparedEvent{} }
func (m *BranchTransactionPreparedEvent) String() string { return proto.CompactTextString(m) }
func (*BranchTransactionPreparedEvent) ProtoMessage()    {}
func (*BranchTransactionPreparedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *BranchTransactionPreparedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BranchTransactionPreparedEvent.Unmarshal(m, b)
}
func (m *BranchTransactionPreparedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BranchTransactionPreparedEvent.Marshal(b, m, deterministic)
}
func (m *BranchTransactionPreparedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BranchTransactionPreparedEvent.Merge(m, src)
}
func (m *BranchTransactionPreparedEvent) XXX_Size() int {
	return xxx_messageInfo_BranchTransactionPreparedEvent.Size(m)
}
func (m *BranchTransactionPreparedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_BranchTransactionPreparedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_BranchTransactionPreparedEvent proto.InternalMessageInfo

func (m *BranchTransactionPreparedEvent) GetPrimaryPrepareTxId() *TransactionID {
	if m != nil {
		return m.PrimaryPrepareTxId
	}
	return nil
}

func (m *BranchTransactionPreparedEvent) GetCommitTx() *BranchTransaction {
	if m != nil {
		return m.CommitTx
	}
	return nil
}

func (m *BranchTransactionPreparedEvent) GetRollbackTx() *BranchTransaction {
	if m != nil {
		return m.RollbackTx
	}
	return nil
}

type GlobalTransactionStatus struct {
	PrimaryPrepareTxId   *TransactionID              `protobuf:"bytes,1,opt,name=primary_prepare_tx_id,json=primaryPrepareTxId,proto3" json:"primary_prepare_tx_id,omitempty"`
	Status               GlobalTransactionStatusType `protobuf:"varint,2,opt,name=status,proto3,enum=pb.GlobalTransactionStatusType" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *GlobalTransactionStatus) Reset()         { *m = GlobalTransactionStatus{} }
func (m *GlobalTransactionStatus) String() string { return proto.CompactTextString(m) }
func (*GlobalTransactionStatus) ProtoMessage()    {}
func (*GlobalTransactionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *GlobalTransactionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalTransactionStatus.Unmarshal(m, b)
}
func (m *GlobalTransactionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalTransactionStatus.Marshal(b, m, deterministic)
}
func (m *GlobalTransactionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalTransactionStatus.Merge(m, src)
}
func (m *GlobalTransactionStatus) XXX_Size() int {
	return xxx_messageInfo_GlobalTransactionStatus.Size(m)
}
func (m *GlobalTransactionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalTransactionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalTransactionStatus proto.InternalMessageInfo

func (m *GlobalTransactionStatus) GetPrimaryPrepareTxId() *TransactionID {
	if m != nil {
		return m.PrimaryPrepareTxId
	}
	return nil
}

func (m *GlobalTransactionStatus) GetStatus() GlobalTransactionStatusType {
	if m != nil {
		return m.Status
	}
	return GlobalTransactionStatusType_INIT
}

type VerifyInfo struct {
	Contract             string   `protobuf:"bytes,1,opt,name=Contract,proto3" json:"Contract,omitempty"`
	Function             string   `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyInfo) Reset()         { *m = VerifyInfo{} }
func (m *VerifyInfo) String() string { return proto.CompactTextString(m) }
func (*VerifyInfo) ProtoMessage()    {}
func (*VerifyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{12}
}

func (m *VerifyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyInfo.Unmarshal(m, b)
}
func (m *VerifyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyInfo.Marshal(b, m, deterministic)
}
func (m *VerifyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyInfo.Merge(m, src)
}
func (m *VerifyInfo) XXX_Size() int {
	return xxx_messageInfo_VerifyInfo.Size(m)
}
func (m *VerifyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyInfo proto.InternalMessageInfo

func (m *VerifyInfo) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *VerifyInfo) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.GlobalTransactionStatusType", GlobalTransactionStatusType_name, GlobalTransactionStatusType_value)
	proto.RegisterEnum("pb.BranchTransactionResponse_Status", BranchTransactionResponse_Status_name, BranchTransactionResponse_Status_value)
	proto.RegisterType((*Lock)(nil), "pb.Lock")
	proto.RegisterType((*GlobalTransaction)(nil), "pb.GlobalTransaction")
	proto.RegisterType((*Invocation)(nil), "pb.Invocation")
	proto.RegisterType((*BranchTransaction)(nil), "pb.BranchTransaction")
	proto.RegisterType((*BranchTransactionResponse)(nil), "pb.BranchTransactionResponse")
	proto.RegisterType((*PrimaryLockMeta)(nil), "pb.PrimaryLockMeta")
	proto.RegisterType((*URI)(nil), "pb.URI")
	proto.RegisterType((*TransactionID)(nil), "pb.TransactionID")
	proto.RegisterType((*PrimaryTransactionPreparedEvent)(nil), "pb.PrimaryTransactionPreparedEvent")
	proto.RegisterType((*PrimaryTransactionConfirmedEvent)(nil), "pb.PrimaryTransactionConfirmedEvent")
	proto.RegisterType((*BranchTransactionPreparedEvent)(nil), "pb.BranchTransactionPreparedEvent")
	proto.RegisterType((*GlobalTransactionStatus)(nil), "pb.GlobalTransactionStatus")
	proto.RegisterType((*VerifyInfo)(nil), "pb.VerifyInfo")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x5f, 0xc7, 0x69, 0xfe, 0xbc, 0xec, 0xb6, 0xe9, 0xc0, 0x0a, 0xb7, 0x6c, 0x69, 0xd6, 0x02,
	0x54, 0x71, 0xf0, 0x4a, 0x45, 0x0b, 0x02, 0x71, 0xc9, 0x3a, 0x01, 0x2c, 0x6d, 0xdb, 0x68, 0xe2,
	0x82, 0x38, 0x45, 0x8e, 0x33, 0x49, 0xac, 0xc6, 0x1e, 0x6b, 0x66, 0x52, 0x52, 0x3e, 0x01, 0x27,
	0x0e, 0x9c, 0x38, 0xf3, 0x21, 0xb8, 0xf3, 0x15, 0xf8, 0x44, 0x68, 0xc6, 0x63, 0xaf, 0xbb, 0x69,
	0x42, 0x0f, 0xe5, 0xb6, 0xa7, 0xf8, 0xbd, 0xf9, 0xbd, 0xdf, 0xbc, 0x7f, 0xf3, 0x0b, 0xb4, 0xc4,
	0x4d, 0x4a, 0xb8, 0x93, 0x32, 0x2a, 0x28, 0xaa, 0xa4, 0xe3, 0xc3, 0xe3, 0x19, 0xa5, 0xb3, 0x05,
	0x79, 0xa1, 0x3c, 0xe3, 0xe5, 0xf4, 0x85, 0x88, 0x62, 0xc2, 0x45, 0x10, 0xa7, 0x19, 0xc8, 0xfe,
	0xdd, 0x80, 0xea, 0x6b, 0x1a, 0x5e, 0xa1, 0x1e, 0x3c, 0x4d, 0x59, 0x14, 0x07, 0xec, 0x66, 0x94,
	0x32, 0x92, 0x06, 0x8c, 0x8c, 0xc4, 0x6a, 0x14, 0x4d, 0x2c, 0xa3, 0x63, 0x9c, 0xb4, 0x4e, 0xf7,
	0x9d, 0x74, 0xec, 0xf8, 0x2c, 0x48, 0x78, 0x10, 0x8a, 0x88, 0x26, 0x5e, 0x0f, 0x23, 0x8d, 0x1f,
	0x64, 0x70, 0x7f, 0xe5, 0x4d, 0xd0, 0x11, 0x40, 0xca, 0xc8, 0xf5, 0x88, 0x8b, 0x40, 0x10, 0xab,
	0xd2, 0x31, 0x4e, 0x1e, 0xe3, 0xa6, 0xf4, 0x0c, 0xa5, 0x03, 0x7d, 0x02, 0xbb, 0xcb, 0x74, 0x12,
	0x88, 0x28, 0x99, 0x69, 0x88, 0xa9, 0x20, 0x4f, 0x72, 0xaf, 0x82, 0xd9, 0xbf, 0x56, 0x61, 0xff,
	0xbb, 0x05, 0x1d, 0x07, 0x8b, 0xd2, 0x8d, 0x0f, 0x94, 0x61, 0x17, 0xf6, 0x73, 0x96, 0x90, 0xc6,
	0x71, 0x24, 0x46, 0x62, 0xa5, 0x12, 0x6d, 0x9d, 0x3e, 0x95, 0x0c, 0xaf, 0x58, 0x90, 0x84, 0xf3,
	0x12, 0x0f, 0xde, 0xd3, 0x78, 0x57, 0xc1, 0xfd, 0x15, 0xea, 0xc3, 0x7b, 0x39, 0x05, 0xa3, 0x8b,
	0xc5, 0x38, 0x08, 0xaf, 0x24, 0x89, 0xb9, 0x8d, 0x24, 0xbf, 0x14, 0xeb, 0x00, 0x7f, 0x85, 0x5c,
	0x40, 0x63, 0x85, 0x2b, 0x95, 0xc3, 0xad, 0x6a, 0xc7, 0xdc, 0xcc, 0xd2, 0xce, 0x02, 0x8a, 0x7a,
	0xb8, 0x2c, 0x47, 0x93, 0x14, 0xd5, 0x70, 0x6b, 0x67, 0x1b, 0xc7, 0x5e, 0x86, 0xcf, 0xab, 0xe1,
	0xb2, 0x1c, 0x4d, 0x51, 0xaa, 0x86, 0x5b, 0xb5, 0x6d, 0x24, 0xfa, 0xd2, 0x37, 0xd5, 0x70, 0x39,
	0x7a, 0x21, 0x16, 0xa3, 0x39, 0x89, 0x66, 0x73, 0x61, 0xd5, 0x3b, 0xc6, 0x49, 0x15, 0x37, 0x85,
	0x58, 0x7c, 0xaf, 0x1c, 0xe8, 0x25, 0x34, 0xe4, 0xb1, 0xdc, 0x3f, 0xab, 0xa1, 0x3a, 0x75, 0xe8,
	0x64, 0xcb, 0xe9, 0xe4, 0xcb, 0xe9, 0xf8, 0xf9, 0x72, 0xe2, 0xba, 0x10, 0x0b, 0x69, 0xd9, 0x03,
	0x00, 0x2f, 0xb9, 0xa6, 0x61, 0xa0, 0x56, 0xe0, 0x10, 0x1a, 0x21, 0x4d, 0x04, 0x0b, 0x42, 0xa1,
	0xa6, 0xde, 0xc4, 0x85, 0x8d, 0x10, 0x54, 0xa7, 0xcb, 0x24, 0x54, 0xb3, 0x6c, 0x62, 0xf5, 0x2d,
	0x7d, 0x01, 0x9b, 0x71, 0xcb, 0xec, 0x98, 0x27, 0x8f, 0xb1, 0xfa, 0xb6, 0xaf, 0x60, 0x7f, 0xad,
	0x1e, 0xf4, 0x29, 0xec, 0xfc, 0xc7, 0x2e, 0x55, 0x85, 0xdc, 0x1e, 0x07, 0x20, 0x2a, 0xd2, 0xd1,
	0x6b, 0xb3, 0x2b, 0xc1, 0x6f, 0x92, 0xc4, 0x25, 0x84, 0xfd, 0xa7, 0x01, 0x07, 0xeb, 0xdd, 0x23,
	0x3c, 0xa5, 0x09, 0x27, 0x68, 0x17, 0x2a, 0xfa, 0xca, 0x26, 0xae, 0x44, 0x13, 0xf4, 0x0d, 0xd4,
	0xe4, 0xab, 0x58, 0x72, 0xc5, 0xbc, 0x7b, 0xfa, 0xf1, 0xdd, 0xcd, 0xd7, 0xe1, 0xce, 0x50, 0x61,
	0xb1, 0x8e, 0x41, 0xef, 0xc3, 0x4e, 0xca, 0x28, 0x9d, 0xea, 0x37, 0x95, 0x19, 0xf6, 0x73, 0xa8,
	0x65, 0x38, 0xd4, 0x82, 0xfa, 0xf0, 0xd2, 0x75, 0xfb, 0xc3, 0x61, 0xfb, 0x11, 0x02, 0xa8, 0x7d,
	0xdb, 0xf5, 0x5e, 0xf7, 0x7b, 0x6d, 0xc3, 0xfe, 0x0a, 0xf6, 0x06, 0xd9, 0x76, 0x4a, 0x25, 0x38,
	0x23, 0x22, 0x40, 0x6d, 0x30, 0x57, 0x45, 0x6a, 0xf2, 0x53, 0xb2, 0x87, 0xf3, 0x20, 0x4a, 0x74,
	0x7f, 0x33, 0xc3, 0x7e, 0x09, 0xe6, 0x25, 0xf6, 0x90, 0x05, 0xf5, 0x84, 0x88, 0x9f, 0x29, 0xbb,
	0xd2, 0x21, 0xb9, 0xb9, 0x21, 0xec, 0x6b, 0x78, 0x72, 0xab, 0xbb, 0xe8, 0x00, 0xcc, 0x25, 0x8b,
	0x74, 0xf7, 0xeb, 0xb2, 0xec, 0x4b, 0xec, 0x61, 0xe9, 0xd3, 0x4d, 0xaa, 0xe4, 0x4d, 0xb2, 0xff,
	0xaa, 0xc0, 0xb1, 0x4e, 0xb7, 0xc4, 0xa1, 0x9f, 0xc4, 0xa4, 0x7f, 0x4d, 0x12, 0xf1, 0x4e, 0x2a,
	0xee, 0x90, 0x0a, 0xfb, 0x6f, 0x03, 0x3a, 0xeb, 0x8d, 0x73, 0x69, 0x32, 0x8d, 0x58, 0x7c, 0x47,
	0xe7, 0xc2, 0xec, 0xe4, 0xbe, 0x9d, 0xd3, 0x44, 0xaa, 0x73, 0x3f, 0xc2, 0xd1, 0x6d, 0x55, 0xa2,
	0xec, 0xb6, 0xb8, 0x54, 0xb6, 0xa5, 0x7e, 0x50, 0x56, 0xa8, 0x0b, 0x56, 0x12, 0x19, 0xfb, 0x1f,
	0x03, 0x3e, 0x5a, 0x0b, 0xf8, 0x3f, 0x66, 0x7f, 0x0a, 0xcd, 0x7b, 0xce, 0xbc, 0x11, 0xe6, 0xc3,
	0xfe, 0x02, 0x5a, 0xf7, 0x1e, 0x32, 0xb0, 0xa2, 0x2a, 0xfb, 0x0f, 0x03, 0x3e, 0x58, 0xfb, 0xbb,
	0xd3, 0x8f, 0xf6, 0x61, 0xaa, 0xf9, 0xf2, 0x2d, 0x61, 0x39, 0x96, 0x61, 0x1b, 0xae, 0xf4, 0x6f,
	0x52, 0x92, 0x6b, 0x8a, 0xdd, 0x03, 0xf8, 0x81, 0xb0, 0x68, 0x7a, 0xe3, 0x25, 0x53, 0x2a, 0xe5,
	0xd7, 0x7d, 0x4b, 0x7e, 0x73, 0x5b, 0x9e, 0x49, 0xc9, 0x2d, 0x74, 0xb1, 0x89, 0x0b, 0xfb, 0xb3,
	0xdf, 0x0c, 0xf8, 0x70, 0xcb, 0x6d, 0xa8, 0x01, 0x55, 0xef, 0xdc, 0xf3, 0xdb, 0x8f, 0x50, 0x07,
	0x9e, 0x0d, 0xb0, 0x77, 0xd6, 0xc5, 0x3f, 0x8d, 0x7c, 0xdc, 0x3d, 0x1f, 0x76, 0x5d, 0xdf, 0xbb,
	0x38, 0x1f, 0x0d, 0x70, 0x7f, 0xd0, 0xc5, 0x52, 0xac, 0xd0, 0x73, 0x38, 0xba, 0x0b, 0xe1, 0x5e,
	0x9c, 0x9d, 0x79, 0xbe, 0xdf, 0xef, 0xb5, 0x2b, 0x9b, 0x48, 0xdc, 0xee, 0xb9, 0xdb, 0x97, 0x8a,
	0x67, 0xbe, 0x7a, 0x06, 0x87, 0x21, 0x8d, 0x9d, 0x5f, 0xe6, 0xd1, 0x6c, 0x19, 0x39, 0x21, 0xa3,
	0x9c, 0xc7, 0x84, 0xcf, 0xf5, 0x3f, 0x51, 0x4d, 0xfd, 0x7c, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x53, 0xcb, 0xfb, 0x27, 0x4e, 0x09, 0x00, 0x00,
}
